apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-limits
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "contribflow.labels" . | nindent 4 }}
data:
  limits.yaml: |
    {{- toYaml .Values.limits | nindent 4 }}
