apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "contribflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "postgres.password is required" .Values.postgres.password | quote }}
